# Generated by Django 4.0.3 on 2022-04-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gameroom_alter_game_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='turn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='turn1',
            field=models.BooleanField(default=False),
        ),
    ]
