# Generated by Django 4.0.3 on 2022-04-07 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_gamestate_turn_gamestate_turn1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='palifico',
        ),
    ]
